#ifndef CONF_H
#define CONF_H

#define COMMAND_AREA_TIMER_RESOLUTION 10 //ms
#define DATA_AREA_TIMESTAMP_UPDATE_PERIOD 100 //ms
#define PORT_HANDLER_READ_PERIOD 100 //ms
#define DIRECT_AREA_HISTORY_SIZE 20

#endif // CONF_H
